import sys; sys.path.insert(0, r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox")
exec(open(r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox\tool_base.py", encoding="utf-8-sig").read())

# UUID
W("uuid-generator", "UUID 生成器", "在线生成UUID v4，支持批量生成。", "🆔", "UUID 生成器",
'<div class="card"><button class="btn btn-primary" onclick="gen()" style="width:100%;margin-bottom:12px">🔄 生成 UUID v4</button><div class="result" id="r"><button class="copy-btn" onclick="copy(this,r.innerText.trim())">📋 复制</button>点击按钮生成</div><button class="btn btn-outline" onclick="genBatch()" style="width:100%;margin-top:12px">📦 批量生成10个</button></div><script>function uuid(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var r=Math.random()*16|0;return(c=="x"?r:r&0x3|0x8).toString(16)})}function gen(){r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>"+uuid()}function genBatch(){r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>"+Array.from({length:10},uuid).join("\\n")}gen();function copy(btn,t){navigator.clipboard.writeText(t);btn.textContent="✅ 已复制";setTimeout(function(){btn.textContent="📋 复制"},1500)}</script>')

# Lorem Ipsum
W("lorem-ipsum", "Lorem Ipsum 生成器", "生成中英文占位文本，自定义段落数。", "📄", "Lorem Ipsum 生成器",
'<div class="card"><label>段落数：<span id="pv">3</span></label><input type="range" id="ps" min="1" max="20" value="3"><div style="display:flex;gap:8px;margin-bottom:12px"><button class="btn btn-primary" onclick="gen()" style="flex:1">🔄 生成英文</button><button class="btn btn-outline" onclick="genCN()" style="flex:1">🇨🇳 生成中文</button></div><div class="result" style="max-height:400px;overflow:auto" id="r"><button class="copy-btn" onclick="copy(this,r.innerText.trim())">📋 复制</button></div></div><script>var lorem="Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum".split(" ");var cn="设计是一种永无止境的探索过程每一次创作都是对未知的挑战我们通过视觉语言传达思想用色彩和形态构建沟通的桥梁好的设计不仅美观更能解决问题提升用户体验在数字时代设计变得更加多元化和互动性人工智能正在改变设计的方式让创意不再受限于技术门槛每个人都可以成为创造者".split("");function genP(tx,w){var n=+ps.value,o=[];for(var i=0;i<n;i++){var p=[];for(var j=0;j<w;j++)p.push(tx[Math.floor(Math.random()*tx.length)]);o.push(p.join(""))}return o.join("\\n\\n")}function gen(){r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>"+genP(lorem,50)}function genCN(){r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>"+genP(cn,30)}ps.oninput=function(){pv.textContent=this.value};gen();function copy(btn,t){navigator.clipboard.writeText(t);btn.textContent="✅ 已复制";setTimeout(function(){btn.textContent="📋 复制"},1500)}</script>')

# Case Converter
W("case-converter", "大小写转换器", "一键转换英文大小写、驼峰、下划线等格式。", "🔤", "大小写转换器",
'<div class="card"><textarea id="inp" placeholder="输入英文文本..." style="min-height:100px"></textarea><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px"><button class="btn btn-outline" onclick="cv(\'upper\')">UPPERCASE</button><button class="btn btn-outline" onclick="cv(\'lower\')">lowercase</button><button class="btn btn-outline" onclick="cv(\'title\')">Title Case</button><button class="btn btn-outline" onclick="cv(\'sentence\')">Sentence case</button><button class="btn btn-outline" onclick="cv(\'camel\')">camelCase</button><button class="btn btn-outline" onclick="cv(\'snake\')">snake_case</button></div><div class="result" id="r" style="display:none"><button class="copy-btn" onclick="copy(this,r.innerText.trim())">📋 复制</button></div></div><script>function cv(t){var v=inp.value,o="";if(t=="upper")o=v.toUpperCase();else if(t=="lower")o=v.toLowerCase();else if(t=="title")o=v.replace(/\w\S*/g,function(w){return w.charAt(0).toUpperCase()+w.substr(1).toLowerCase()});else if(t=="sentence")o=v.toLowerCase().replace(/(^\s*|[.!?]\s+)([a-z])/g,function(_,s,l){return s+l.toUpperCase()});else if(t=="camel")o=v.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g,function(_,c){return c.toUpperCase()});else if(t=="snake")o=v.toLowerCase().replace(/\s+/g,"_").replace(/[^a-z0-9_]/g,"");r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>"+o;r.style.display="block"}function copy(btn,t){navigator.clipboard.writeText(t);btn.textContent="✅ 已复制";setTimeout(function(){btn.textContent="📋 复制"},1500)}</script>')

# Percentage
W("percentage-calc", "百分比计算器", "快速计算百分比、折扣、涨跌幅。", "💯", "百分比计算器",
'<div class="card"><div class="r"><input id="n1" type="number" placeholder="数值" value="200"><span style="font-size:1.2rem;font-weight:700">的</span><input id="n2" type="number" placeholder="百分比" value="15"><span style="font-size:1.2rem;font-weight:700">%</span></div><div style="font-size:1.4rem;text-align:center;font-weight:800;padding:16px;background:#eef2ff;border-radius:10px;color:var(--accent)" id="rp">= 30</div><div style="display:flex;gap:8px;margin-top:16px"><button class="btn btn-outline" id="b1" style="flex:1;background:var(--accent);color:#fff">% 占比</button><button class="btn btn-outline" id="b2" style="flex:1">🏷️ 折扣</button><button class="btn btn-outline" id="b3" style="flex:1">📈 涨跌幅</button></div></div><script>var md="pct";function calc(){var a=+n1.value||0,b=+n2.value||0,r;if(md=="pct")r=a*b/100,rp.textContent="= "+r.toFixed(2);else if(md=="discount")r=a*(1-b/100),rp.textContent="折后价: "+r.toFixed(2);else r=(b-a)/a*100,rp.textContent="涨跌: "+r.toFixed(2)+"%"}[n1,n2].forEach(function(e){e.oninput=calc});b1.onclick=function(){md="pct";calc();b1.style.background="var(--accent)";b1.style.color="#fff";b2.style.background="#fff";b2.style.color="var(--accent)";b3.style.background="#fff";b3.style.color="var(--accent)"};b2.onclick=function(){md="discount";calc();b2.style.background="var(--accent)";b2.style.color="#fff";b1.style.background="#fff";b1.style.color="var(--accent)";b3.style.background="#fff";b3.style.color="var(--accent)"};b3.onclick=function(){md="change";calc();b3.style.background="var(--accent)";b3.style.color="#fff";b1.style.background="#fff";b1.style.color="var(--accent)";b2.style.background="#fff";b2.style.color="var(--accent)"};calc()</script>')

print("Batch 1 done")
