import sys; sys.path.insert(0, r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox")
exec(open(r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox\tool_base.py", encoding="utf-8-sig").read())

# Random Number
W("random-number", "随机数生成器", "自定义范围生成随机数，可批量可去重。", "🎲", "随机数生成器",
'<div class="card"><div class="r"><label style="min-width:60px">范围</label><input id="mn" type="number" value="1" style="width:120px"><span>—</span><input id="mx" type="number" value="100" style="width:120px"></div><div class="r"><label style="min-width:60px">数量</label><input id="cn" type="number" value="1" style="width:120px"><label style="margin-left:16px"><input type="checkbox" id="un" style="width:auto">去重</label></div><button class="btn btn-primary" onclick="gen()" style="width:100%;margin-bottom:12px">🎲 生成随机数</button><div class="result" id="r"><button class="copy-btn" onclick="copy(this,r.innerText.trim())">📋 复制</button>点击生成</div></div><script>function gen(){var mn=+document.getElementById("mn").value,mx=+document.getElementById("mx").value,cn=+document.getElementById("cn").value,un=document.getElementById("un").checked;if(cn>mx-mn+1&&un){r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>范围不够";return}var ns=[];if(un){var pool=[];for(var i=mn;i<=mx;i++)pool.push(i);for(i=0;i<cn;i++){var idx=Math.floor(Math.random()*pool.length);ns.push(pool.splice(idx,1)[0])}}else{for(i=0;i<cn;i++)ns.push(Math.floor(Math.random()*(mx-mn+1)+mn))}r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>"+ns.join(", ")}gen();function copy(b,t){navigator.clipboard.writeText(t);b.textContent="✅ 已复制";setTimeout(function(){b.textContent="📋 复制"},1500)}</script>')

# Stopwatch
W("stopwatch", "在线秒表", "精准在线秒表，支持计次和重置。", "⏱️", "在线秒表",
'<div class="card"><div style="font-size:3.5rem;text-align:center;font-family:Courier New,monospace;font-weight:700;padding:20px;background:#1e293b;color:#22c55e;border-radius:12px" id="dp">00:00.00</div><div style="display:flex;gap:8px;margin-top:16px"><button class="btn btn-primary" onclick="tg()" id="sb" style="flex:1">▶ 开始</button><button class="btn btn-outline" onclick="lp()" style="flex:1">🏁 计次</button><button class="btn btn-outline" onclick="rst()" style="flex:1">🔄 重置</button></div><div style="margin-top:16px;max-height:200px;overflow:auto" id="ls"></div></div><script>var rn=false,st=0,el=0,iv;function fm(ms){var m=Math.floor(ms/60000),s=Math.floor((ms%60000)/1000),cs=Math.floor((ms%1000)/10);return String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")+"."+String(cs).padStart(2,"0")}function up(){dp.textContent=fm(el+(rn?Date.now()-st:0))}function tg(){if(rn){el+=Date.now()-st;clearInterval(iv);sb.textContent="▶ 开始";sb.className="btn btn-primary"}else{st=Date.now();iv=setInterval(up,10);sb.textContent="⏸ 暂停";sb.className="btn btn-outline"}rn=!rn}function lp(){if(!el&&!rn)return;var t=rn?el+Date.now()-st:el,d=document.createElement("div");d.style.cssText="padding:8px 12px;border-bottom:1px solid var(--border);font-family:Courier New;display:flex;justify-content:space-between";d.innerHTML="<span>计次 "+(ls.children.length+1)+"</span><span style=color:var(--accent);font-weight:700>"+fm(t)+"</span>";ls.prepend(d)}function rst(){rn=false;clearInterval(iv);el=0;dp.textContent="00:00.00";sb.textContent="▶ 开始";sb.className="btn btn-primary";ls.innerHTML=""}</script>')

# Timestamp
W("timestamp-converter", "时间戳转换器", "Unix时间戳与日期互转，支持多时区。", "⏰", "时间戳转换器",
'<div class="card"><label>时间戳（秒）</label><div class="r"><input id="ts" type="number" placeholder="Unix时间戳"><button class="btn btn-primary" onclick="td()" style="width:auto;white-space:nowrap">→ 转日期</button></div><div class="result" id="tsr"><button class="copy-btn" onclick="copy(this,tsr.innerText.trim())">📋 复制</button>等待输入</div><div style="margin-top:20px"><label>日期时间</label></div><input id="di" type="datetime-local"><button class="btn btn-primary" onclick="dt()" style="width:100%;margin-top:8px">→ 转时间戳</button><div class="result" id="dtr"><button class="copy-btn" onclick="copy(this,dtr.innerText.trim())">📋 复制</button>等待输入</div></div><script>document.getElementById("ts").value=Math.floor(Date.now()/1000);function td(){var ts=+document.getElementById("ts").value;if(!ts)return;var d=new Date(ts*1000);tsr.innerHTML="<button class=copy-btn onclick=\\"copy(this,tsr.innerText.trim())\\">📋 复制</button>"+d.toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"})+" (北京时间)\\n"+d.toISOString()+" (UTC)\\n毫秒: "+(ts*1000)}function dt(){var v=di.value;if(!v)return;var d=new Date(v),ts=Math.floor(d.getTime()/1000);dtr.innerHTML="<button class=copy-btn onclick=\\"copy(this,dtr.innerText.trim())\\">📋 复制</button>秒: "+ts+"\\n毫秒: "+d.getTime()+"\\n"+d.toISOString()}td();di.value=new Date().toISOString().slice(0,16);function copy(b,t){navigator.clipboard.writeText(t);b.textContent="✅ 已复制";setTimeout(function(){b.textContent="📋 复制"},1500)}</script>')

# URL Encoder
W("url-encoder", "URL 编解码", "URL编码/解码，参数解析，开发者必备。", "🔗", "URL 编解码",
'<div class="card"><div style="display:flex;gap:0;margin-bottom:12px;border-radius:10px;overflow:hidden;border:1px solid var(--border)"><button class="btn" onclick="md=\'encode\';up()" id="be" style="flex:1;border-radius:0;background:var(--accent);color:#fff">🔒 编码</button><button class="btn" onclick="md=\'decode\';up()" id="bd" style="flex:1;border-radius:0;background:#fff;color:var(--accent)">🔓 解码</button></div><textarea id="inp" placeholder="输入文本或URL..." style="min-height:100px"></textarea><div class="result" id="r" style="display:none"><button class="copy-btn" onclick="copy(this,r.innerText.trim())">📋 复制</button></div></div><script>var md="encode";function up(){var t=inp.value,o="";if(md=="encode")o=encodeURIComponent(t);else{try{o=decodeURIComponent(t)}catch(e){o="解码错误: "+e.message}}r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>"+o;r.style.display="block"}inp.oninput=up;inp.value="https://example.com?q=你好&lang=zh";up();function copy(b,t){navigator.clipboard.writeText(t);b.textContent="✅ 已复制";setTimeout(function(){b.textContent="📋 复制"},1500)}</script>')

# HTML Entity
W("html-entity", "HTML 实体转义", "HTML特殊字符编码/解码，防XSS注入。", "🏷️", "HTML 实体转义",
'<div class="card"><div style="display:flex;gap:0;margin-bottom:12px;border-radius:10px;overflow:hidden;border:1px solid var(--border)"><button class="btn" onclick="md=\'encode\';up()" id="be" style="flex:1;border-radius:0;background:var(--accent);color:#fff">🔒 转义</button><button class="btn" onclick="md=\'decode\';up()" id="bd" style="flex:1;border-radius:0;background:#fff;color:var(--accent)">🔓 还原</button></div><textarea id="inp" placeholder="输入HTML代码..." style="min-height:100px"></textarea><div class="result" id="r" style="display:none"><button class="copy-btn" onclick="copy(this,r.innerText.trim())">📋 复制</button></div></div><script>var md="encode";function enc(s){var d=document.createElement("div");d.textContent=s;return d.innerHTML}function dec(s){var d=document.createElement("div");d.innerHTML=s;return d.textContent}function up(){var t=inp.value,o="";if(md=="encode")o=enc(t);else o=dec(t);r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>"+o;r.style.display="block"}inp.oninput=up;inp.value="<div class=\\"greeting\\">Hello & welcome!</div>";up();function copy(b,t){navigator.clipboard.writeText(t);b.textContent="✅ 已复制";setTimeout(function(){b.textContent="📋 复制"},1500)}</script>')

print("Batch 2 done")
