import sys; sys.path.insert(0, r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox")
exec(open(r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox\tool_base.py", encoding="utf-8-sig").read())

# Gradient
W("gradient-generator", "CSS 渐变生成器", "可视化创建CSS渐变色，一键复制代码。", "🌈", "CSS 渐变生成器",
'<div class="card"><div style="height:180px;border-radius:12px;margin-bottom:16px" id="pv"></div><div class="r"><label style="min-width:60px">颜色1</label><input type="color" id="c1" value="#6366f1" style="width:80px;height:40px;padding:2px"><label style="min-width:60px">颜色2</label><input type="color" id="c2" value="#a855f7" style="width:80px;height:40px;padding:2px"></div><div class="r"><label style="min-width:60px">角度</label><input type="range" id="ag" min="0" max="360" value="135" style="flex:1"><span id="av" style="min-width:40px">135°</span></div><div style="display:flex;gap:6px;margin-bottom:12px"><button class="btn btn-outline" id="bl" style="flex:1;background:var(--accent);color:#fff" onclick="st(\'linear\')">线性渐变</button><button class="btn btn-outline" id="br" style="flex:1" onclick="st(\'radial\')">径向渐变</button></div><div class="result" id="cd" style="color:#22c55e"><button class="copy-btn" onclick="copy(this,cd.innerText.trim())">📋 复制</button></div></div><script>var tp="linear",ag=135;function up(){var c1=c1.value,c2=c2.value,css=tp=="linear"?"linear-gradient("+ag+"deg, "+c1+", "+c2+")":"radial-gradient(circle, "+c1+", "+c2+")";pv.style.background=css;cd.innerHTML="<button class=copy-btn onclick=\\"copy(this,cd.innerText.trim())\\">📋 复制</button>background: "+css+";"}function st(t){tp=t;bl.style.background=t=="linear"?"var(--accent)":"#fff";bl.style.color=t=="linear"?"#fff":"var(--accent)";br.style.background=t=="radial"?"var(--accent)":"#fff";br.style.color=t=="radial"?"#fff":"var(--accent)";up()}c1.oninput=up;c2.oninput=up;ag.oninput=function(){ag=+this.value;av.textContent=ag+"°";up()};up();function copy(b,t){navigator.clipboard.writeText(t);b.textContent="✅ 已复制";setTimeout(function(){b.textContent="📋 复制"},1500)}</script>')

# Emoji Search
W("emoji-search", "Emoji 搜索器", "按关键词搜索Emoji，一键复制。", "🔎", "Emoji 搜索器",
'<div class="card"><input id="s" placeholder="搜索 Emoji..." style="margin-bottom:12px"><div style="display:flex;flex-wrap:wrap;gap:4px;max-height:400px;overflow:auto" id="g"></div></div><script>var es=[["😀😃😄😁😅😂🤣😊😇🙂😉😌😍🥰😘😗😋😛😜🤪😝🤑🤗🤭🤫🤔🤐😐😑😶😏😒🙄😬😮😯😲😳🥺😢😭😤😡🤬😈👿💀☠️💩🤡👻👽🤖😺😸😹😻😼😽🙀😿😾","face"],["👍👎👏🙌🤝✌️🤞🤟🤘👌🤌🤏✋👋🤚🖐️🖖👈👉👆👇☝️💪🤳","hand"],["🐶🐱🐭🐹🐰🦊🐻🐼🐨🐯🦁🐮🐷🐸🐵🐔🐧🐦🐤🦆🦅🦉🦇🐺🐗🐴🦄🐝🐛🦋🐌🐞🐜🦟🦗🕷️🦂🐢🐍🦎🦖🦕🐙🦑🦐🦞🦀🐡🐠🐟🐬🐳🐋🦈🐊🐅🐆🦓🦍🦧🐘🦛🦏🐪🐫🦒🦘🐃🐂🐄🐎🐖🐏🐑🦙🐐🦌🐕🐩🦮🐕‍🦺🐈🐈‍⬛🦃🦚🦜🦢🦩🕊️🐇🦝🦨🦡🦦🦥🐁🐀🐿️🦔","animal"],["🍏🍎🍐🍊🍋🍌🍉🍇🍓🫐🍈🍒🍑🥭🍍🥥🥝🍅🍆🥑🥦🥬🥒🌶️🫑🌽🥕🫒🧄🧅🥔🍠🥐🍞🥖🥨🧀🥚🍳🧈🥞🧇🥓🥩🍗🍖🦴🌭🍔🍟🍕🫓🥪🥙🧆🌮🌯🫔🥗🥘🫕🥫🍝🍜🍲🍛🍣🍱🥟🦪🍤🍙🍚🍘🍥🥠🥮🍢🍡🍧🍨🍦🥧🧁🍰🎂🍮🍭🍬🍫🍿🍩🍪🌰🥜🍯🥛🍼☕🫖🍵🍶🍺🍻🥂🍷🫗🥃🍸🍹🧉🍾🧊🥄🍴🍽️🥣🥡🥢🧂","food"],["❤️🧡💛💚💙💜🖤🤍🤎💔❣️💕💞💓💗💖💘💝💟☮️✝️☪️🕉️☸️✡️🔯🕎☯️☦️🛐⛎♈♉♊♋♌♍♎♏♐♑♒♓🆔⚛️🉑☢️☣️📴📳🈶🈚🈸🈺🈷️✴️🆚💮🉐㊙️㊗️🈴🈵🈹🈲🅰️🅱️🆎🆑🅾️🆘❌⭕🛑⛔📛🚫💯♻️✅❇️✳️❎🌐💠Ⓜ️🌀💤🏧🚾♿🅿️🛗🈳🈂️🛂🛃🛄🛅🚹🚺🚼⚧🚻🚮🎦📶🈁🔣ℹ️🔤🔡🔠🆖🆗🆙🆒🆕🆓0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣🔟🔢#️⃣*️⃣▶️⏸️⏹️⏺️⏭️⏮️⏩⏪⏫⏬◀️🔼🔽➡️⬅️⬆️⬇️↗️↘️↙️↖️↕️↔️↪️↩️⤴️⤵️🔀🔁🔂🔄🔃🎵🎶➕➖➗✖️♾️💲💱™️©️®️〰️➰➿🔚🔙🔛🔝🔜✔️☑️🔘🔴🟠🟡🟢🔵🟣⚫⚪🟤🔺🔻🔸🔹🔶🔷🔳🔲▪️▫️◾◽◼️◻️🟥🟧🟨🟩🟦🟪⬛⬜🟫","symbol"]];var all=[];es.forEach(function(g){[...g[0]].forEach(function(e){all.push({e:e,c:g[1]})})});function render(){var q=s.value.toLowerCase(),f=all.filter(function(x){return!q||x.e.includes(q)||x.c.includes(q)});g.innerHTML=f.slice(0,200).map(function(x){return "<span style=font-size:1.8rem;cursor:pointer;padding:4px onclick=\\"cp(\\"+x.e+"\\)\\" title="+x.e+">"+x.e+"</span>"}).join("")}function cp(e){navigator.clipboard.writeText(e);var t=document.createElement("div");t.textContent="已复制 "+e;t.style.cssText="position:fixed;top:20px;left:50%;transform:translateX(-50%);background:#1e293b;color:#fff;padding:8px 20px;border-radius:8px;z-index:100;animation:fo 1.5s forwards";document.body.appendChild(t);setTimeout(function(){t.remove()},1500)}s.oninput=render;render();</script><style>@keyframes fo{0%{opacity:1}70%{opacity:1}100%{opacity:0}}</style>')

# Unit Converter
W("unit-converter", "单位换算器", "长度/重量/温度/面积/速度在线换算。", "📐", "单位换算器",
'<div class="card"><select id="cat" onchange="sw()" style="margin-bottom:12px"><option value="length">📏 长度</option><option value="weight">⚖️ 重量</option><option value="temp">🌡️ 温度</option><option value="area">📐 面积</option><option value="speed">🚀 速度</option></select><div class="r"><input id="iv" type="number" value="1" style="flex:1"><select id="fu" style="width:auto;flex:1"></select></div><div style="text-align:center;font-size:1.5rem;padding:8px">=</div><div class="r"><input id="ov" readonly style="flex:1;background:#eef2ff"><select id="tu" style="width:auto;flex:1"></select></div></div><script>var u={length:{m:1,km:1000,cm:0.01,mm:0.001,mi:1609.34,yd:0.9144,ft:0.3048,in:0.0254,li:500},weight:{kg:1,g:0.001,mg:0.000001,t:1000,lb:0.4536,oz:0.02835,jin:0.5},temp:{},area:{m2:1,km2:1e6,ha:10000,mu:666.67,ft2:0.0929},speed:{ms:1,kmh:0.2778,mph:0.447,kn:0.5144}};var tc={c:"摄氏度",f:"华氏度",k:"开尔文"};function cv(){var c=cat.value;if(c=="temp"){var v=+iv.value,f=fu.value,t=tu.value,r=v;if(f=="f")r=(v-32)*5/9;else if(f=="k")r=v-273.15;if(t=="f")r=r*9/5+32;else if(t=="k")r=r+273.15;ov.value=r.toFixed(4)}else{var un=u[c],f=fu.value,t=tu.value,r=+iv.value*un[f]/un[t];ov.value=parseFloat(r.toPrecision(10))}}function sw(){var c=cat.value,op="";if(c=="temp"){for(var k in tc)op+="<option value="+k+">"+tc[k]+"</option>"}else{for(var k in u[c])op+="<option value="+k+">"+k+"</option>"}fu.innerHTML=op;tu.innerHTML=op;if(c!="temp")tu.selectedIndex=1;cv()}iv.oninput=cv;fu.onchange=cv;tu.onchange=cv;sw()</script>')

# CSV to JSON
W("csv-to-json", "CSV 转 JSON", "CSV和JSON格式互转，数据处理必备。", "📊", "CSV ↔ JSON",
'<div class="card"><div style="display:flex;gap:6px;margin-bottom:12px"><button class="btn btn-primary" onclick="c2j()" style="flex:1">CSV → JSON</button><button class="btn btn-outline" onclick="j2c()" style="flex:1">JSON → CSV</button></div><textarea id="inp" placeholder="粘贴CSV或JSON数据..." style="min-height:120px;font-family:Courier New,monospace;font-size:.85rem"></textarea><div class="result" id="r" style="display:none"><button class="copy-btn" onclick="copy(this,r.innerText.trim())">📋 复制</button></div><div id="err" style="color:#ef4444;font-size:.85rem;margin-top:4px"></div></div><script>function c2j(){try{var t=inp.value.trim(),lines=t.split("\\n"),hd=lines[0].split(",").map(function(h){return h.trim()}),result=[];for(var i=1;i<lines.length;i++){if(!lines[i].trim())continue;var v=lines[i].split(","),o={};hd.forEach(function(h,j){o[h]=v[j]?v[j].trim():""});result.push(o)}show(JSON.stringify(result,null,2))}catch(e){err.textContent="错误: "+e.message}}function j2c(){try{var d=JSON.parse(inp.value);if(!Array.isArray(d)){err.textContent="请输入JSON数组";return}var ks=Object.keys(d[0]),lines=[ks.join(",")];d.forEach(function(r){lines.push(ks.map(function(k){return JSON.stringify(r[k]||"")}).join(","))});show(lines.join("\\n"))}catch(e){err.textContent="错误: "+e.message}}function show(s){r.innerHTML="<button class=copy-btn onclick=\\"copy(this,r.innerText.trim())\\">📋 复制</button>"+s;r.style.display="block";err.textContent=""}function copy(b,t){navigator.clipboard.writeText(t);b.textContent="✅ 已复制";setTimeout(function(){b.textContent="📋 复制"},1500)}inp.value="name,age,city\\n张三,28,北京\\n李四,32,上海\\n王五,25,深圳";c2j()</script>')

# Cron Parser
W("cron-parser", "Cron 表达式解析", "解析Cron定时表达式，显示执行时间。", "🕐", "Cron 表达式解析",
'<div class="card"><input id="cr" placeholder="Cron表达式，如：0 8 * * *" value="0 8 * * *" style="font-family:Courier New,monospace"><button class="btn btn-primary" onclick="pa()" style="width:100%;margin-top:8px">🔍 解析</button><div id="r" style="margin-top:12px;padding:16px;background:#eef2ff;border-radius:10px;min-height:60px;font-size:.9rem;line-height:1.8"></div></div><script>var dm={0:"分钟",1:"小时",2:"日",3:"月",4:"星期"};function pa(){var p=cr.value.trim().split(/\\s+/);if(p.length<5){r.innerHTML="请输入至少5位Cron表达式";return}var h="<b>解析结果：</b><br>";for(var i=0;i<5;i++)h+=dm[i]+": <b>"+desc(p[i],i)+"</b><br>";h+="<br><b>下次执行（北京时间）：</b><br>"+nr(p,5).join("<br>");r.innerHTML=h}function desc(p,i){if(p=="*")return "每"+(i==2?"天":i==3?"月":"");if(p.includes(","))return p.split(",").join(", ");if(p.includes("/")){var a=p.split("/");return "从"+a[0]+"开始每"+a[1]+(i==0?"分钟":i==1?"小时":"")}if(p.includes("-")){var a=p.split("-");return a[0]+"到"+a[1]}return p}function nr(p,n){var rs=[],d=new Date();d.setSeconds(0,0);for(var i=0;i<300;i++){d.setMinutes(d.getMinutes()+1);var m=d.getMinutes(),h=d.getHours(),dom=d.getDate(),mon=d.getMonth()+1,dow=d.getDay();if(mt(p[0],m)&&mt(p[1],h)&&mt(p[2],dom)&&mt(p[3],mon)&&mt(p[4],dow)){rs.push(d.toLocaleString("zh-CN",{timeZone:"Asia/Shanghai"}));if(rs.length>=n)break}}return rs}function mt(e,v){if(e=="*")return true;if(e.includes(","))return e.split(",").includes(String(v));if(e.includes("/")){var a=e.split("/"),s=a[0]=="*"?0:+a[0];return v>=s&&(v-s)%(+a[1])==0}if(e.includes("-")){var a=e.split("-");return v>=+a[0]&&v<=+a[1]}return +e==v}pa()</script>')

print("Batch 3 done")
