import sys; sys.path.insert(0, r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox")
exec(open(r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox\tool_base.py", encoding="utf-8-sig").read())

# Markdown - media query in body style tag
W("markdown-preview", "Markdown 预览器", "实时编辑和预览Markdown，支持多种语法。", "📖", "Markdown 预览器",
'<style>.md-wrap{display:flex;gap:12px;height:400px}.md-wrap textarea,.md-wrap #pv{flex:1;height:100%}@media(max-width:640px){.md-wrap{flex-direction:column;height:auto!important}.md-wrap textarea,.md-wrap #pv{height:200px!important}}</style><div class="card"><div class="md-wrap"><textarea id="inp" placeholder="输入 Markdown..." style="resize:none;font-family:Courier New,monospace;font-size:.85rem"></textarea><div id="pv" style="border:1px solid var(--border);border-radius:10px;padding:16px;overflow:auto;background:#fff;line-height:1.6"></div></div></div><script>function md(t){return t.replace(/^### (.+)$/gm,"<h3 style=margin:12px 0 6px>$1</h3>").replace(/^## (.+)$/gm,"<h2 style=margin:16px 0 8px>$1</h2>").replace(/^# (.+)$/gm,"<h1 style=margin:20px 0 10px>$1</h1>").replace(/\*\*(.+?)\*\*/g,"<b>$1</b>").replace(/\*(.+?)\*/g,"<i>$1</i>").replace(/`(.+?)`/g,"<code style=background:#eef2ff;padding:2px 6px;border-radius:4px;font-size:.85em>$1</code>").replace(/^\- (.+)$/gm,"<li style=margin-left:20px>$1</li>").replace(/\[(.+?)\]\((.+?)\)/g,"<a href=\"$2\" style=color:var(--accent) target=_blank>$1</a>").replace(/\n\n/g,"<br><br>").replace(/^---$/gm,"<hr style=margin:16px 0;border:0;border-top:1px solid var(--border)>").replace(/^> (.+)$/gm,"<blockquote style=border-left:3px solid var(--accent);padding-left:12px;color:var(--muted);margin:8px 0>$1</blockquote>")}inp.oninput=function(){pv.innerHTML=md(this.value)};inp.value="# Markdown 预览器\n\n欢迎使用 **AI工具箱**！\n\n## 功能\n- 实时预览\n- 支持标题/加粗/斜体\n- 代码块支持\n- [链接支持](https://freetools-daily-h3v5.vercel.app)\n\n> 这是一个引用块\n\n---\n\n试试编辑左边的文本吧！";inp.oninput()</script>')

# Regex
W("regex-tester", "正则表达式测试", "在线测试正则表达式，实时高亮匹配。", "🔍", "正则表达式测试",
'<div class="card"><label>正则表达式</label><input id="rx" value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}" placeholder="输入正则..." style="font-family:Courier New,monospace;margin-bottom:12px"><label>测试文本</label><textarea id="tx" style="min-height:100px" placeholder="输入测试文本..."></textarea><div style="display:flex;gap:8px;margin-top:12px"><input id="fl" placeholder="标志：g i m" value="g" style="flex:1"><button class="btn btn-primary" onclick="test()" style="width:auto">🔍 测试</button></div><div style="margin-top:12px;padding:12px;background:#eef2ff;border-radius:10px;min-height:40px;font-size:.9rem" id="info"></div><div id="hl" style="margin-top:12px;padding:16px;background:#fff;border:1px solid var(--border);border-radius:10px;min-height:80px;line-height:1.8;white-space:pre-wrap;word-break:break-all"></div></div><script>function test(){try{var r=new RegExp(rx.value,fl.value),t=tx.value,ms=[],m;while((m=r.exec(t))!==null){ms.push({i:m.index,l:m[0].length,s:m[0]});if(!fl.value.includes("g"))break}info.innerHTML="<b>"+ms.length+"</b> 个匹配";var h="",last=0;ms.forEach(function(m){h+=esc(t.slice(last,m.i))+"<mark style=background:#fde68a;padding:1px 2px;border-radius:2px>"+esc(m.s)+"</mark>";last=m.i+m.l});h+=esc(t.slice(last));hl.innerHTML=h||"无匹配"}catch(e){info.innerHTML="❌ "+e.message}}function esc(s){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}tx.value="联系邮箱：zhangsan@example.com\n备用邮箱：lisi@test.org\n无效：not-an-email\n更多：admin@ai-toolbox.cn";test()</script>')

# IP Lookup
W("ip-lookup", "IP 地址查询", "查询IP归属地、运营商信息。", "🌍", "IP 地址查询",
'<div class="card"><input id="ip" placeholder="输入IP地址，留空查询当前IP"><button class="btn btn-primary" onclick="lk()" style="width:100%;margin-top:8px">🔍 查询</button><div id="r" style="margin-top:12px;padding:16px;background:#eef2ff;border-radius:10px;min-height:60px;font-size:.9rem;line-height:1.8">点击查询</div></div><script>async function lk(){var ip=document.getElementById("ip").value.trim(),url=ip?"https://api.ip.sb/geoip/"+ip:"https://api.ip.sb/geoip";r.innerHTML="查询中...";try{var res=await fetch(url),d=await res.json();r.innerHTML="<b>IP:</b> "+d.ip+"<br><b>国家:</b> "+d.country+"<br><b>城市:</b> "+d.city+"<br><b>ISP:</b> "+d.isp+"<br><b>经纬度:</b> "+d.latitude+", "+d.longitude+"<br><b>时区:</b> "+d.timezone}catch(e){r.innerHTML="查询失败，请检查网络"}}</script>')

# UA Parser
W("user-agent", "User-Agent 解析器", "解析浏览器UA，显示设备和系统信息。", "🖥️", "User-Agent 解析器",
'<div class="card"><textarea id="ua" style="min-height:80px;font-family:Courier New,monospace;font-size:.8rem" placeholder="输入 User-Agent 字符串..."></textarea><button class="btn btn-primary" onclick="pa()" style="width:100%;margin-top:8px">🔍 解析</button><div id="r" style="margin-top:12px;padding:16px;background:#eef2ff;border-radius:10px;min-height:60px;line-height:1.8;font-size:.9rem"></div></div><script>function pa(){var u=ua.value,b="",o="",d="Desktop";if(u.includes("Edg/"))b="Edge "+u.match(/Edg\/(\d+)/)[1];else if(u.includes("Chrome/")&&!u.includes("Edg/"))b="Chrome "+u.match(/Chrome\/(\d+)/)[1];else if(u.includes("Firefox/"))b="Firefox "+u.match(/Firefox\/(\d+)/)[1];else if(u.includes("Safari/")&&!u.includes("Chrome"))b="Safari "+(u.match(/Version\/([\d.]+)/)||["","?"])[1];if(u.includes("Windows"))o="Windows";else if(u.includes("Mac OS"))o="macOS";else if(u.includes("Android")){o="Android";d="Mobile"}else if(u.includes("iPhone")||u.includes("iPad")){o="iOS";d=u.includes("iPad")?"Tablet":"Mobile"}else if(u.includes("Linux"))o="Linux";r.innerHTML="<b>浏览器:</b> "+b+"<br><b>操作系统:</b> "+o+"<br><b>设备类型:</b> "+d}ua.value="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0";pa()</script>')

# Diff Checker
W("diff-checker", "文本差异对比", "对比两段文本差异，高亮增删改。", "↔️", "文本差异对比",
'<div class="card"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><div><label>原始文本</label><textarea id="t1" style="min-height:120px;font-family:Courier New,monospace;font-size:.8rem" placeholder="粘贴原始文本..."></textarea></div><div><label>对比文本</label><textarea id="t2" style="min-height:120px;font-family:Courier New,monospace;font-size:.8rem" placeholder="粘贴新文本..."></textarea></div></div><button class="btn btn-primary" onclick="df()" style="width:100%;margin-top:12px">↔️ 对比差异</button><div id="r" style="margin-top:12px;padding:16px;border:1px solid var(--border);border-radius:10px;background:#fff;min-height:60px;font-family:Courier New,monospace;font-size:.85rem;line-height:1.6;white-space:pre-wrap;max-height:300px;overflow:auto"></div></div><script>function lcs(a,b){var m=a.length,n=b.length,dp=Array.from({length:m+1},function(){return Array(n+1).fill(0)});for(var i=1;i<=m;i++)for(var j=1;j<=n;j++)dp[i][j]=a[i-1]==b[j-1]?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1]);var rs=[],i=m,j=n;while(i>0&&j>0){if(a[i-1]==b[j-1]){rs.unshift(["=",a[i-1]]);i--;j--}else if(dp[i-1][j]>dp[i][j-1]){rs.unshift(["-",a[i-1]]);i--}else{rs.unshift(["!",b[j-1]]);j--}}while(i>0){rs.unshift(["-",a[i-1]]);i--}while(j>0){rs.unshift(["!",b[j-1]]);j--}return rs}function df(){var l1=t1.value.split("\n"),l2=t2.value.split("\n"),d=lcs(l1,l2),h="";d.forEach(function(p){var c=p[0]=="-"?"#fecaca":p[0]=="!"?"#bbf7d0":"transparent",s=p[0]=="-"?"- ":p[0]=="!"?"+ ":"  ";h+="<div style=background:"+c+";padding:1px 4px;font-family:Courier New>"+s+esc(p[1])+"</div>"});r.innerHTML=h||"文本完全相同"}function esc(s){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}t1.value="Hello World\nThis is a test\nGoodbye";t2.value="Hello World\nThis is a test (updated)\nSee you later";df()</script>')

print("Batch 4a done")
