import sys; sys.path.insert(0, r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox")
exec(open(r"C:\Users\15166\Documents\Codex\2026-06-14\codex-codex\aitoolbox\tool_base.py", encoding="utf-8-sig").read())

W("barcode-generator", "条形码生成器", "在线生成条形码并下载PNG图片。", "📊", "条形码生成器",
'<div class="card"><input id="cd" value="1234567890" placeholder="输入条形码内容..." style="margin-bottom:12px;font-family:Courier New,monospace"><button class="btn btn-primary" onclick="gen()" style="width:100%;margin-bottom:12px">🔢 生成条形码</button><canvas id="cv" style="width:100%;max-width:400px;display:block;margin:0 auto"></canvas><button class="btn btn-outline" onclick="dl()" style="width:100%;margin-top:8px">⬇ 下载</button></div><script>function gen(){var t=cd.value;if(!t)return;var w=400,h=150,c=cv.getContext("2d");cv.width=w;cv.height=h;c.fillStyle="#fff";c.fillRect(0,0,w,h);c.fillStyle="#000";var bits=[],total=0;for(var i=0;i<t.length;i++){var code=t.charCodeAt(i).toString(2).padStart(8,"0");bits.push("1"+code+"0");total+=code.length+2}bits.push("11");total+=2;var bw=Math.max(1,Math.floor((w-60)/total)),sx=(w-total*bw)/2,x=sx;c.fillStyle="#000";for(var j=0;j<bits.length;j++){var str=bits[j];for(var k=0;k<str.length;k++){if(str[k]=="1")c.fillRect(x+k*bw,20,bw,100)}x+=str.length*bw}c.fillStyle="#000";c.font="14px monospace";c.textAlign="center";c.fillText(t,w/2,145)}function dl(){var a=document.createElement("a");a.href=cv.toDataURL("image/png");a.download="barcode.png";a.click()}gen()</script>')

W("image-cropper", "图片裁剪工具", "在线裁剪图片，自定义宽高。", "✂️", "图片裁剪工具",
'<div class="card"><div style="border:2px dashed var(--border);border-radius:12px;padding:40px;text-align:center;cursor:pointer;margin-bottom:12px" id="dz" onclick="fi.click()"><div style="font-size:3rem">📁</div><p style="color:var(--muted)">点击上传图片</p><input type="file" id="fi" accept="image/*" style="display:none"></div><div id="ed" style="display:none"><div style="position:relative;display:inline-block;max-width:100%"><img id="im" style="max-width:100%;max-height:400px;display:block"></div><div style="display:flex;gap:8px;margin-top:12px"><input id="cw" type="number" placeholder="宽" value="200" style="flex:1"><input id="ch" type="number" placeholder="高" value="200" style="flex:1"><button class="btn btn-primary" onclick="cr()" style="width:auto">✂️ 裁剪</button></div><canvas id="cv" style="max-width:100%;margin-top:12px;display:none"></canvas><button class="btn btn-outline" onclick="dl()" style="width:100%;margin-top:8px;display:none" id="db">⬇ 下载</button></div></div><script>var im=document.getElementById("im"),cv=document.getElementById("cv");fi.onchange=function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(ev){im.src=ev.target.result;im.onload=function(){ed.style.display="block";dz.style.display="none"}};r.readAsDataURL(f)};function cr(){var iw=im.naturalWidth,ih=im.naturalHeight,cw=+document.getElementById("cw").value,ch=+document.getElementById("ch").value,sx=(iw-cw)/2,sy=(ih-ch)/2;cv.width=cw;cv.height=ch;cv.getContext("2d").drawImage(im,sx,sy,cw,ch,0,0,cw,ch);cv.style.display="block";db.style.display="block"}function dl(){var a=document.createElement("a");a.href=cv.toDataURL();a.download="cropped.png";a.click()}</script>')

W("meme-generator", "表情包生成器", "上传图片，添加文字，一键生成表情包。", "😂", "表情包生成器",
'<div class="card"><div style="border:2px dashed var(--border);border-radius:12px;padding:30px;text-align:center;cursor:pointer;margin-bottom:12px" id="dz" onclick="fi.click()"><div style="font-size:3rem">📁</div><p style="color:var(--muted)">点击上传图片制作表情包</p><input type="file" id="fi" accept="image/*" style="display:none"></div><div id="ed" style="display:none"><canvas id="cv" style="max-width:100%;display:block;border-radius:8px;margin:0 auto"></canvas><input id="tt" placeholder="上方文字（可选）" style="margin-top:8px"><input id="bt" placeholder="下方文字（可选）" style="margin-top:8px"><div class="r"><label style="min-width:40px">字号</label><input type="range" id="fs" min="20" max="80" value="40" style="flex:1"><span id="sv">40</span></div><button class="btn btn-primary" onclick="dr()" style="width:100%;margin-top:8px">🔄 预览</button><button class="btn btn-outline" onclick="dl()" style="width:100%;margin-top:8px">⬇ 下载</button></div></div><script>var img=null;fi.onchange=function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(ev){img=new Image();img.onload=function(){ed.style.display="block";dz.style.display="none";dr()};img.src=ev.target.result};r.readAsDataURL(f)};function dr(){if(!img)return;var w=img.width,h=img.height,mw=600,s=1;if(w>mw){s=mw/w;w=mw;h=Math.floor(img.height*s)}cv.width=w;cv.height=h;var c=cv.getContext("2d");c.drawImage(img,0,0,w,h);var fs=+document.getElementById("fs").value,tt=document.getElementById("tt").value,bt=document.getElementById("bt").value;c.fillStyle="#fff";c.strokeStyle="#000";c.lineWidth=fs/8;c.font="bold "+fs+"px sans-serif";c.textAlign="center";if(tt){c.strokeText(tt,w/2,fs+10);c.fillText(tt,w/2,fs+10)}if(bt){c.strokeText(bt,w/2,h-20);c.fillText(bt,w/2,h-20)}}fs.oninput=function(){sv.textContent=this.value;dr()};tt.oninput=dr;bt.oninput=dr;function dl(){var a=document.createElement("a");a.href=cv.toDataURL();a.download="meme.png";a.click()}</script>')

print("All 22 tools regenerated!")
